spring:

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/mall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: product
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


server:
  port: 10000

logging:
  level:
    com.junling.online_mall: debug